export default [
    "#PMQs",
    "2007",
    "2007Scape",
    "284",
    "AHYEON",
    "AI",
    "ANews earthquake video",
    "ANews turkey",
    "ASA",
    "Alexander The Great",
    "Area",
    "Assist",
    "BABYMON",
    "BABYMONSTER",
    "BAEMON",
    "BBC Sport",
    "BBC iPlayer",
    "BBQ",
    "BT Sport",
    "Big Show",
    "Boss",
    "Bossing",
    "British TV",
    "British TV Shows",
    "Burnley",
    "Burnley FC",
    "Burnley Football Club",
    "Burnley Goals",
    "Burnley Highlights",
    "CHIQUITA",
    "Calfreezy",
    "Challenge",
    "Champion",
    "Champions League",
    "Championship",
    "Channel Youtube DougDoug",
    "Clarets",
    "Clarets Player",
    "Cycling",
    "David Ornstein",
    "Declan Rice",
    "Destiny",
    "DougDoug",
    "DougDoug Youtube Channel",
    "Dream",
    "EFL",
    "EPL Goals",
    "EPL Highlights",
    "EPL highlights 1920",
    "End",
    "England",
    "English",
    "Episode",
    "Erik Ten Hag",
    "Erik ten Hag",
    "European Super League",
    "FIFA World Cup",
    "Featherweight",
    "Folding phone",
    "Football",
    "Football Fails",
    "Football League",
    "Football Skill",
    "Footy",
    "Freestyle Football",
    "Friends",
    "Funny",
    "Galaxy Fold",
    "Game",
    "Gary Neville",
    "Gear",
    "Gnonto",
    "Goldbridge",
    "HARAM",
    "Heavyweight",
    "How to",
    "Huawei",
    "IBM",
    "Im pregnant",
    "Intel",
    "Ironman",
    "Islam Makhachev",
    "Items",
    "Jack Della Maddalena",
    "Jadon Sancho",
    "Jamie Carragher",
    "Jedi Survivor Game Play",
    "Jedi Survivor Gameplay",
    "Jedi Survivor Koboh Gameplay",
    "Josh",
    "Josh “CC0” Emmett",
    "Justin Bad Man",
    "Korean",
    "KoreanEnglish",
    "LUFC",
    "Leeds",
    "Leeds United",
    "Lewis Capaldi",
    "Lightweight",
    "London",
    "MNF",
    "MUFC",
    "MUTV",
    "Man",
    "Man City",
    "Man City Premier League",
    "Man City banned",
    "Man City charges",
    "Man City explained",
    "Man City relegated",
    "Man U",
    "Man United",
    "Man United 2-2 Leeds",
    "Man Utd",
    "Man Utd News",
    "Man Utd live stream",
    "Man Utd vs Leeds United",
    "Manchester City",
    "Manchester United",
    "Manchester United 2-2 Leeds",
    "Manchester United 2-2 Leeds highlights",
    "Manchester United 2020",
    "Manchester United Breaking News",
    "Manchester United Latest News",
    "Manchester United Leeds United",
    "Manchester United News",
    "Manchester United TV",
    "Manchester United Transfer News",
    "Manchester United vs Leeds United",
    "Marco Mengoni",
    "Marcus Rashford",
    "Mark Goldbridge",
    "Mason Greenwood",
    "Max",
    "Maxed UIM",
    "Maxing",
    "Michael McIntyre",
    "Monday Night Football",
    "Mory",
    "Mory Ironman",
    "Morytania",
    "Morytania Ironman",
    "Morytania UIM",
    "NASA",
    "Nathan Tella",
    "OSRS",
    "OSRS Settled",
    "Old",
    "Old Trafford",
    "Ollie",
    "PHARITA",
    "Parker Porter",
    "Prank",
    "Premier League",
    "Premier League Goals",
    "Premier League Highlights",
    "Progress",
    "RORA",
    "RS3",
    "RUKA",
    "Randy Rudeboy Brown",
    "Rashford",
    "Rebel",
    "Rebel FC",
    "Respawn Star Wars",
    "Rice",
    "Rodriguez",
    "Runescape",
    "SBS",
    "Sancho",
    "Sancho goal",
    "School",
    "Sean Dyche",
    "Send to all",
    "Settled",
    "Settled UIM",
    "Settledrs",
    "Skilling",
    "Sky",
    "Sky Sports",
    "Sky Sports Football",
    "Sky Sports live",
    "Soccer",
    "Soccer Fails",
    "Soccer Skills",
    "South Korea",
    "Sport",
    "Sports",
    "Star Wars",
    "Star Wars Jedi Survivor",
    "Star Wars Jedi Survivor Gameplay",
    "Star Wars Survivor Gameplay",
    "Star Wars games",
    "Stretford Paddock",
    "Swampletics",
    "TIFO football",
    "TSMC",
    "Tafa",
    "Tekkers",
    "Ten Hag",
    "Ten Hag Man Utd",
    "Ten Hag Man Utd interview",
    "Ten Hag press conference",
    "The Kick Off",
    "The Legend of Zelda: Tears of the Kingdom nintendo",
    "The Legend of Zelda: Tears of the Kingdom nintendo switch",
    "The Legend of Zelda: Tears of the Kingdom official trailer",
    "The Legend of Zelda: Tears of the Kingdom trailer",
    "The Overlap",
    "The United Stand",
    "Tips",
    "Toilet",
    "Tour de France",
    "Transfer",
    "Trick Shots",
    "Tricks",
    "True Geordie",
    "Turf Moor",
    "UCL",
    "UIM",
    "UIM Maxing",
    "UIM Settled",
    "Ultimate",
    "United",
    "United Kingdom",
    "United Stand",
    "Video",
    "Vincent Kompany",
    "Volkanovski",
    "Vox.com",
    "Watch British TV Online",
    "Watch British TV Shows Online",
    "Watch UK TV Online",
    "Welterweight",
    "West Ham United",
    "Yair El Pantera",
    "Yiannimize Customs is officially open for business",
    "YouTuber",
    "a$ap rocky",
    "action",
    "adventure",
    "alison hammond",
    "ameen al-dakhil",
    "amoled",
    "android",
    "apex",
    "apex gameplay trailer",
    "apex legends",
    "apex legends revelry",
    "apex legends season 16",
    "apex legends season 16 trailer",
    "apex legends tdm",
    "apex legends team deathmatch",
    "apex legends trailer",
    "apex revelry",
    "apex season 16",
    "apex season 16 trailer",
    "apex trailer",
    "apex トレーラー",
    "apple",
    "ask ornstein",
    "battle royale game",
    "best folding phone",
    "biden",
    "biff",
    "bleacher report",
    "br",
    "breath of the wild",
    "breath of the wild randomizer",
    "cal kestis",
    "cancelled",
    "cantanti",
    "canzoni",
    "car wrap",
    "carrera gt",
    "challenge",
    "championship",
    "channel points",
    "chelsea",
    "chicken",
    "china",
    "chinese",
    "chinese fabrication",
    "cold war",
    "comedy",
    "computer",
    "computer chips",
    "computers",
    "crafts",
    "debut",
    "demuro",
    "dily projects",
    "diy",
    "diy activities",
    "diy slime",
    "do it yourself",
    "doorman",
    "doug de muro",
    "doug demuro",
    "doug doug",
    "dougdoug twitch",
    "dougdoug twitch chat",
    "due vite",
    "earthquake",
    "earthquake video",
    "eastern europe news",
    "economics",
    "electricity",
    "emotional response",
    "energy",
    "engineering",
    "englishman",
    "enzo fernandez",
    "epl",
    "epl highlights 1920",
    "epl other 1920",
    "erik ten hag",
    "etihad",
    "experiment",
    "experiments",
    "explain",
    "explainer",
    "fa cup",
    "fab",
    "fabs",
    "fallen order 2",
    "farbrizio romano",
    "feel good",
    "festival",
    "festival di sanremo 2023",
    "ffp",
    "financial fair play",
    "finding out Im pregnant",
    "finding out Im pregnant and telling my boyfriend",
    "first pregnancy",
    "flexible display",
    "foldable phone",
    "fontaines dc",
    "food",
    "football",
    "football debate",
    "football reaction",
    "freezy",
    "fried",
    "friends",
    "fun",
    "funny",
    "g nev",
    "galaxy flip",
    "galaxy fold 4",
    "galaxy fold 5",
    "game",
    "gameplay",
    "gameplay apex legends",
    "gameplay trailer apex legends",
    "gary neville",
    "geopolitics",
    "gorillaz",
    "grocery store",
    "guardiola",
    "handcraft",
    "highlights",
    "hill",
    "holly willoughby",
    "hong kong",
    "honor magic vs",
    "how to",
    "i feel so good",
    "idles",
    "ign",
    "interview",
    "iphone",
    "itv",
    "jamie carragher",
    "janitor",
    "japan",
    "jazzy",
    "jedi fallen order",
    "jedi fallen order 2",
    "jedi survivor",
    "jedi survivor gameplay",
    "kareem scoring record",
    "korean",
    "lakers",
    "laugh",
    "lebron breaks kareem scoring record",
    "lebron highlights",
    "lebron james",
    "lebron kareem",
    "lebron kareem scoring record",
    "lebron lakers",
    "lebron passes kareem",
    "lebron scoring record",
    "lebron vs. okc thunder",
    "life hacks",
    "lifehacks",
    "liga inggris",
    "los angeles lakers",
    "lyle foster",
    "magic vs",
    "malatya earthquake",
    "malatya turkey",
    "man city",
    "manchester",
    "manchester city",
    "microchips",
    "middle east",
    "middle east news",
    "military",
    "mma",
    "mudryk",
    "mura masa",
    "national security",
    "nba",
    "nev",
    "new",
    "new breath of the wild game trailer",
    "new team",
    "new zelda game nintendo switch",
    "new zelda game trailer",
    "nintendo",
    "nintendo switch",
    "nothing great about britain",
    "nuclear",
    "nvidia",
    "overlap",
    "overlap interview",
    "phillip schofield",
    "phones",
    "pl",
    "play",
    "porsche carrera gt",
    "ppv",
    "prank",
    "pranks",
    "premier league",
    "premier league highlights",
    "punk slowthai",
    "radio",
    "raw reaction",
    "remastered legend classes",
    "respawn apex legends",
    "revelry apex legends",
    "revelry gameplay trailer",
    "revelry trailer",
    "rpg",
    "sand minecraft",
    "sandacation",
    "sandication",
    "sandition",
    "sandtion",
    "sanremo",
    "sanremo 2023",
    "second earthquake",
    "secret",
    "selfish",
    "semiconductors",
    "sepak bola",
    "shame",
    "sidemen",
    "silicone",
    "skepta",
    "skills",
    "sky sports",
    "sky sports football",
    "slime",
    "slow thai",
    "slowthai",
    "slowthai alternative",
    "slowthai box",
    "slowthai fontaines",
    "slowthai mirrors",
    "slowthai rap",
    "slowthai selfish",
    "slowthai ugly",
    "south korea",
    "staff",
    "star wars",
    "star wars jedi survivor gameplay",
    "star wars jedi survivor part 1",
    "star wars jedi survivor walkthrough part 1",
    "star wars survivor",
    "stream",
    "struggling with fertility",
    "switch",
    "syria earthquake",
    "syria earthquake live",
    "syria news",
    "taiwan",
    "taiwan strait",
    "teardown",
    "tears of the kingdom new trailer",
    "tech",
    "tech wars",
    "technology",
    "television",
    "ten hag",
    "the Athletic",
    "the athletic",
    "the overlap",
    "this morning",
    "this morning funniest moments",
    "this morning interviews",
    "this morning itv",
    "tips",
    "titanium",
    "todd boehly",
    "trade",
    "transfer window",
    "transistors",
    "tricks",
    "trump",
    "turkey earthquake",
    "turkey earthquake live",
    "turkey earthquake video",
    "turkey live",
    "turkey news",
    "turkey rescue",
    "turkey second earthquake",
    "turkey syria",
    "twitch",
    "twitch chat",
    "twitch chat plays",
    "tyron",
    "ufc",
    "ugly",
    "uk bands",
    "uk punk",
    "uk rap",
    "uk rappers",
    "ultimate fighting championship",
    "united states",
    "urban automotive",
    "us",
    "usa",
    "useful things",
    "vehicle wraps",
    "video game",
    "vinyl wrap",
    "vinyl wrapping a car",
    "vlog",
    "vlogging",
    "vlogs",
    "vox",
    "vs Manchester United",
    "war",
    "weapons",
    "world",
    "world news",
    "wrap kings",
    "wrapping a car",
    "xi",
    "yiannimize",
    "zelda",
    "zelda game 2023",
    "zelda game 2023 trailer",
    "zelda randomizer",
    "zerkaa",
    "zerkaa clips",
    "zerkaaclips",
    "zerkaahd",
    "zerkaaplays",
    "zte",
    "エーペックス",
    "남자",
    "도전",
    "라면",
    "로라",
    "루카",
    "매운",
    "미친남자",
    "반응",
    "베몬",
    "베이비몬스터",
    "불닭볶음면",
    "삼겹살",
    "신부님",
    "아사",
    "아현",
    "영국",
    "영국남자",
    "영상",
    "올리",
    "올리아빠",
    "외국",
    "외국인",
    "웃긴",
    "음식",
    "조니",
    "조쉬",
    "조엘",
    "치키타",
    "치킨",
    "크리스",
    "파리타",
    "하람",
    "해물",
];
