name: run_tests
run-name: ${{ github.actor }} runnings tests on commit
on: [push]

jobs:
  run_all_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out respository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pwd ls -al
          pip install -r requirements.txt

      - name: Run test suite
        run: |
          pip install pytest
          pytest