name: Run tests in docker
run-name: ${{ github.actor }} runnings tests in Docker on commit
on: [push]

jobs:
  run_all_tests:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out respository code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t testing_image .

      - name: Run tests inside Docker container
        run: docker run testing_image pytest

