name: Run all tests
run-name: ${{ github.actor }} running all tests
on: 
  push:
    branches:
      - '*'
      - '!main'

jobs:
  run_all_tests:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out respository code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t testing_image .

      - name: Run tests inside Docker container
        run: docker run testing_image pytest